# Load the imfile module to monitor text log files
module(load="imfile")

# Rule for Apache Access Log
input(type="imfile"
      File="/var/log/httpd/access_log"
      Tag="apache-access"
      Severity="info"
      Facility="local6")

# Rule for Apache Error Log
input(type="imfile"
      File="/var/log/httpd/error_log"
      Tag="apache-error"
      Severity="error"
      Facility="local6")
# choose only one from sending methods below & UDP or TCP
# Send local6 facility logs to the Supervisor FORTISIEM via TCP on port 514
#local6.* @@192.168.1.100:514
  
# Send all logs to the Supervisor FORTISIEM via UDP on port 514 (Optional)
#*.* @192.168.1.100:514
  
# Stop processing these logs locally to prevent duplication (Optional)
& stop



